name: Crowdin Action

on:
  push:
    branches: [ master ]

permissions:
  actions: write
  contents: write 
  pull-requests: write

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          config: crowdin.yaml
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: i18n_crowdin_action
          commit_message: 'feat(i18n): add new Crowdin translations'
          create_pull_request: true
          pull_request_title: '[i18n] New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: 801710
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}